//
//  FormTableCell.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.16
//
//

import Foundation

enum InputType {
    // text type enables generic text input
    case text
    // password type enables secure text input
    case password
    // staticText hides place holder view and shows the input field by default
    case staticText
}

/**
 High level construct to create a cell in the form requiring user input.
 */
class FormTableCell {
    
    // The placeholder text that appears on an input field
    var placeHolder: String?
    // The type of input for the input field
    var type: InputType?
    // The default text in the input field
    var staticText: String?
    
    init(placeHolder: String, type: InputType) {
        self.placeHolder = placeHolder
        self.type = type
    }
    
    init(placeHolder: String, staticText: String) {
        self.placeHolder = placeHolder
        self.type = .staticText
        self.staticText = staticText
    }
}
