//
//  TableInputCell.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.16
//
//

import Foundation
import UIKit

/*
 TableInputCell represents the elements of a row in the table view.
 */
class TableInputCell: UITableViewCell {
    
    // the header label of text field when user is making an input
    @IBOutlet weak var headerLabel: UILabel!
    // the text field which contains input from user
    @IBOutlet weak var inputBox: UITextField!
    // the label holding place holder text for an input field
    @IBOutlet weak var placeHolderLabel: UILabel!
    // the view for placeholder text
    @IBOutlet weak var placeHolderView: UIView!
    // the view for header label
    @IBOutlet weak var headerLabelView: UIView!
    // the view for text field input
    @IBOutlet weak var textfieldView: UIView!
    
    // Handle event when user finishes inputting text into a text field
    @IBAction func textEditingDidEnd(_ sender: Any) {
        // If input field empty, reset the placeholder view
        guard let text = inputBox.text, text != "" else {
            self.placeHolderView.alpha = 0
            self.placeHolderView.isHidden = false
            UIView.animate(withDuration: 0.5) {
                self.placeHolderView.alpha = 1
                self.headerLabel.isHidden = true
                self.inputBox.isHidden = true
            }
            return
        }
    }
    
    func onTap() {
        DispatchQueue.main.async(execute: {
            // Hide the placeholder view and show the input field to user
            UIView.transition(with: self.placeHolderView, duration: 0.5, options: UIViewAnimationOptions.transitionCrossDissolve, animations: {
                self.placeHolderView.isHidden = true
                self.headerLabel.isHidden = false
                self.inputBox.isHidden = false
            }, completion: nil)
            
            self.inputBox.becomeFirstResponder()
        })
    }
}
