//
//  ColorThemeSettings.swift
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.16
//

import Foundation
import UIKit
import AWSCore
import AWSCognito

let ColorThemeSettingsTitleTextColorKey = "title_text_color"
let ColorThemeSettingsTitleBarColorKey = "title_bar_color"
let ColorThemeSettingsBackgroundColorKey = "background_color"

let ColorThemeSettingsDefaultTitleTextColor: Int32 = Int32(bitPattern: 0xFFFFFFFF)
let ColorThemeSettingsDefaultTitleBarColor: Int32 = Int32(bitPattern: 0xFFF58535)
let ColorThemeSettingsDefaultBackgroundColor: Int32 = Int32(bitPattern: 0xFFFFFFFF)

class ColorThemeSettings {
    
    var theme: Theme
    static let sharedInstance: ColorThemeSettings = ColorThemeSettings()

    fileprivate init() {
        theme = Theme()
    }
    
    // MARK: - User Settings Functions
    
    func loadSettings(_ completionBlock: @escaping (ColorThemeSettings?, Error?) -> Void) {
        let syncClient: AWSCognito = AWSCognito.default()
        let userSettings: AWSCognitoDataset = syncClient.openOrCreateDataset("user_settings")
        
        userSettings.synchronize().continueWith { (task: AWSTask<AnyObject>) -> Any? in
            if let error = task.error as? NSError {
                print("loadSettings error: \(error)")
                completionBlock(nil, error)
                return nil
            }
            let titleTextColorString: String? = userSettings.string(forKey: ColorThemeSettingsTitleTextColorKey)
            let titleBarColorString: String? = userSettings.string(forKey: ColorThemeSettingsTitleBarColorKey)
            let backgroundColorString: String? = userSettings.string(forKey: ColorThemeSettingsBackgroundColorKey)
            
            if let titleTextColorString = titleTextColorString,
                let titleBarColorString = titleBarColorString,
                let backgroundColorString = backgroundColorString {
                self.theme = Theme(titleTextColor: titleTextColorString.toInt32(),
                                   withTitleBarColor: titleBarColorString.toInt32(),
                                   withBackgroundColor: backgroundColorString.toInt32())
            } else {
                self.theme = Theme()
            }
            completionBlock(self, nil)
            return nil
        }
    }
    
    func saveSettings(_ completionBlock: ((ColorThemeSettings?, Error?) -> Void)?) {
        let syncClient: AWSCognito = AWSCognito.default()
        let userSettings: AWSCognitoDataset = syncClient.openOrCreateDataset("user_settings")
        
        userSettings.setString("\(theme.titleTextColor)", forKey: ColorThemeSettingsTitleTextColorKey)
        userSettings.setString("\(theme.titleBarColor)", forKey: ColorThemeSettingsTitleBarColorKey)
        userSettings.setString("\(theme.backgroundColor)", forKey: ColorThemeSettingsBackgroundColorKey)
        
        userSettings.synchronize().continueWith { (task: AWSTask<AnyObject>) -> Any? in
            if let error = task.error {
                print("saveSettings AWS task error: \(error)")
                completionBlock?(nil, error)
                return nil
            }
            completionBlock?(self, nil)
            return nil
        }
    }
    
    func wipe() {
        AWSCognito.default().wipe()
    }
}


class Theme: NSObject {
    
    fileprivate(set) var titleTextColor: Int32
    fileprivate(set) var titleBarColor: Int32
    fileprivate(set) var backgroundColor: Int32
    
    override init() {
        titleTextColor = ColorThemeSettingsDefaultTitleTextColor
        titleBarColor = ColorThemeSettingsDefaultTitleBarColor
        backgroundColor = ColorThemeSettingsDefaultBackgroundColor
        super.init()
    }
    
    init(titleTextColor: Int32, withTitleBarColor titleBarColor: Int32, withBackgroundColor backgroundColor: Int32) {
        self.titleTextColor = titleTextColor
        self.titleBarColor = titleBarColor
        self.backgroundColor = backgroundColor
        super.init()
    }
}

// MARK: - Utility

extension Int32 {
    public func UIColorFromARGB() -> UIColor {
        let argbValue: Int64 = Int64(self)
        let divider: Float = 255.0
        
        return UIColor(red: CGFloat((Float((argbValue & 0x00FF0000) >> 16)) / divider),
            green: CGFloat((Float((argbValue & 0x0000FF00) >> 8)) / divider),
            blue: CGFloat((Float((argbValue & 0x000000FF) >> 0)) / divider),
            alpha: CGFloat((Float((argbValue & 0xFF000000) >> 24)) / divider))
    }
}

extension String {
    public func toInt32() -> Int32 {
        return Int32(self)!
    }
}
