//
//  UserSettingsViewController.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.16
//

import UIKit

class UserSettingsViewController: UIViewController {
    
    fileprivate var themes: [Theme]!
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let theme0 = Theme(titleTextColor: Int32(bitPattern: 0xFFFFFFFF),
                           withTitleBarColor: Int32(bitPattern: 0xFFF58535),
                           withBackgroundColor: Int32(bitPattern: 0xFFFFFFFF))
        let theme1 = Theme(titleTextColor: Int32(bitPattern: 0xFFDDDDDD),
                           withTitleBarColor: Int32(bitPattern: 0xFF00D2FF),
                           withBackgroundColor: Int32(bitPattern: 0xFFEEEEEE))
        let theme2 = Theme(titleTextColor: Int32(bitPattern: 0xFFFFFFFF),
                           withTitleBarColor: Int32(bitPattern: 0xFF00D2A9),
                           withBackgroundColor: Int32(bitPattern: 0xFFC8FFFF))
        let theme3 = Theme(titleTextColor: Int32(bitPattern: 0xFFFFFF00),
                           withTitleBarColor: Int32(bitPattern: 0xFF000000),
                           withBackgroundColor: Int32(bitPattern: 0xFFFFFFDC))
        
        themes = [theme0, theme1, theme2, theme3]
        loadAppearance()
    }
    
    // MARK: - IBActions
    
    @IBAction func handlerSettings0(_ sender: AnyObject) {
        updateAppearanceWithTheme(self.themes[0])
        saveAppearance(self.themes[0])
    }
    
    @IBAction func handlerSettings1(_ sender: AnyObject) {
        updateAppearanceWithTheme(self.themes[1])
        saveAppearance(self.themes[1])
    }
    
    @IBAction func handlerSettings2(_ sender: AnyObject) {
        updateAppearanceWithTheme(self.themes[2])
        saveAppearance(self.themes[2])
    }
    
    @IBAction func handlerSettings3(_ sender: AnyObject) {
        updateAppearanceWithTheme(self.themes[3])
        saveAppearance(self.themes[3])
    }
    
    // MARK: - Utility Methods
    
    fileprivate func loadAppearance() {
        let settings = ColorThemeSettings.sharedInstance
        settings.loadSettings { (themeSettings: ColorThemeSettings?, error: Error?) in
            guard let themeSettings = themeSettings else {
                print("Failed to load color from dataset: \(error)")
                return
            }
            DispatchQueue.main.async(execute: {
                let theme = themeSettings.theme
                self.updateAppearanceWithTheme(theme)
            })
        }
    }
    
    fileprivate func saveAppearance(_ theme: Theme) {
        let settings: ColorThemeSettings = ColorThemeSettings.sharedInstance
        settings.theme = theme
        settings.saveSettings(nil)
    }
    
    fileprivate func updateAppearanceWithTheme(_ theme: Theme) {
        let titleTextColor =  theme.titleTextColor.UIColorFromARGB()
        navigationController!.navigationBar.barTintColor = theme.titleBarColor.UIColorFromARGB()
        navigationController!.navigationBar.tintColor = titleTextColor
        navigationController!.navigationBar.titleTextAttributes = [NSForegroundColorAttributeName: titleTextColor]
        navigationController?.viewControllers.first?.view.backgroundColor = theme.backgroundColor.UIColorFromARGB()
        view.backgroundColor = theme.backgroundColor.UIColorFromARGB()
    }
    
    fileprivate func showErrorDialog(_ error: NSError) {
        print("User Settings Error: \(error)")
        let alertController = UIAlertController(title: NSLocalizedString("Error", comment: "Title bar for alert dialog."),
                                                message: "User Settings Error: \(error.localizedDescription)",
                                                preferredStyle: .alert)
        let alertAction = UIAlertAction(title: NSLocalizedString("OK", comment: "Button on alert dialog."),
                                        style: .default, handler: nil)
        alertController.addAction(alertAction)
        present(alertController, animated: true, completion: nil)
    }
}
