//
//  NoSQLTableListViewController.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.16
//

import Foundation
import UIKit

class NoSQLTableListViewController: UITableViewController {
    
    fileprivate var tables: [Table]?
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.backBarButtonItem = UIBarButtonItem(title: "Back", style: .plain, target: nil, action: nil)
        tables = NoSQLTableFactory.supportedTables

    }
    
    override func numberOfSections(in tableView: UITableView) -> Int {
        guard let tables = tables else {return 0}
        return tables.count
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 1
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "NoSQLTableListCell", for: indexPath) as! NoSQLTableListCell
        let table = tables![indexPath.section]
        cell.tableNameLabel.text = table.tableDisplayName
        cell.partitionKeyLabel.text = "\(table.tableAttributeName!(table.partitionKeyName)) (\(table.partitionKeyType))"
        cell.sortKeyLabel.text = "-"
        if let sortKey = table.sortKeyName {
            cell.sortKeyLabel.text = "\(table.tableAttributeName!(sortKey)) (\(table.sortKeyType!))"
        }
        cell.numberOfIndexesLabel.text = "\(table.indexes.count)"
        return cell
    }
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        let showQueryResultSeque = "NoSQLShowTableDetailsSegue"
        performSegue(withIdentifier: showQueryResultSeque, sender: tables![indexPath.section])
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let destinationViewController = segue.destination as? NoSQLTableViewController {
            destinationViewController.table = sender as? Table
        }
    }
}

class NoSQLTableListCell: UITableViewCell {

    @IBOutlet weak var tableNameLabel: UILabel!
    @IBOutlet weak var partitionKeyLabel: UILabel!
    @IBOutlet weak var sortKeyLabel: UILabel!
    @IBOutlet weak var numberOfIndexesLabel: UILabel!
}
